# Generated by Django 6.0.3 on 2026-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("Manufacturing", "Manufacturing"),
                            ("Service", "Service"),
                            ("Trading", "Trading"),
                            ("All", "All"),
                        ],
                        max_length=50,
                    ),
                ),
                ("min_turnover", models.FloatField()),
                ("max_turnover", models.FloatField()),
                ("min_loan_amount", models.FloatField()),
                ("max_loan_amount", models.FloatField()),
                ("interest_rate", models.FloatField(help_text="Interest rate in %")),
                (
                    "max_tenure_years",
                    models.IntegerField(help_text="Loan tenure in years"),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
